### PR TITLE
Preserve my current deploy

### LINKED ISSUE #56: I would like to preserve my current deploy dir after $releasesToKeep subsequent failing deploys
I don't know if it is a feature or a joke, but after $releasesToKeep +1 subsequent failing deploys, the current directory will be erased.

### PR DESCRIPTION
**Pull request by piribes**
Putting "grep -v $(basename $(readlink %s))" between "sort" and "head" should fix #56
We also need to pass ($releasesToKeep - 1) to "head -n -%d" because we always grep one result from "sort".

### CODE REVIEW

**Comment by micheleorselli** [comment]
Thank you for providing the fix, would you mind adding a test too?

File: src/Idephix/Extension/Deploy/Deploy.php [hunk 1]
```diff
@@ -241,11 +241,13 @@ public function updateSchema($env = 'dev')
      */
     public function deleteOldReleases($releasesToKeep)
     {
+        if (is_numeric($releasesToKeep)) return;
```
Comment (micheleorselli) [inline src/Idephix/Extension/Deploy/Deploy.php]: don't omit the brackets, it should be 

```php
if (is_numeric($releasesToKeep)) {
  return;
}
```

**Comment by piribes** [comment]
My pleasure.
I have fixed the test and forced a push, let me know if its ok now.

**Comment by piribes** [comment]
@micheleorselli any update ?

**Comment by micheleorselli** [comment]
sorry for the late update, seems good to me, :+1:

**Comment by ProntoPro** [comment]
and now flowers will grow!

**Comment by piribes** [comment]
thank you, @micheleorselli ;)
